apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        app: phone-node
    name: phone-node
    namespace: akka
spec:
    replicas: 1
    selector:
        matchLabels:
            app: phone-node
    template:
        metadata:
            labels:
                app: phone-node
                actorSystemName: showdown
        spec:
            containers:
            -   name: phone-node
                image: clusteringsolutionsshowdown/phone-node:2
                livenessProbe:
                    tcpSocket:
                        port: 8558
                ports:
                # akka remoting
                -   name: remoting
                    containerPort: 2552
                    protocol: TCP
                # akka-management bootstrap
                -   name: bootstrap
                    containerPort: 8558
                    protocol: TCP
                # external http
                -   name: akka-mgmt-http
                    containerPort: 8558
                    protocol: TCP
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pod-reader
    namespace: akka
rules:
-   apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: read-pods
    namespace: akka
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
-   kind: ServiceAccount
    name: default
    namespace: akka
roleRef:
    kind: Role
    name: pod-reader
    apiGroup: rbac.authorization.k8s.io